### ISSUE TITLE
Using notification: "LEAVE_HIDDEN_PAGE" causes Uncaught TypeError

### ISSUE THREAD

**Issue by KimORichter** [sdetweil/MMM-pages#3]
**Describe the bug**
When using notification: "LEAVE_HIDDEN_PAGE", notifications in MMM-OnScreenMenu and MMM-TouchButtons cease sending ALL notifications, except LEAVE_HIDDEN_PAGE.

**To Reproduce**
(Please paste any information on reproducing the issue, for example:)
1. In either MMM-OnScreenMenu and MMM-TouchButtons, using notification: "SHOW_HIDDEN_PAGE" with payload: "screenSaver" or "admin"
2. Click on either menu option. Page changes correctly.
3. Click on "LEAVE_HIDDEN_PAGE", Previous Page returns to view.
4. Click on any other MMM-OnScreenMenu and MMM-TouchButtons button, No notification is sent.
5. Error message in MM Inspection:

OSM Menu Item Clicked: notify1
{"title":"Sleep Page","icon":"refresh","notification":"SHOW_HIDDEN_PAGE","payload":"screenSaver"}
MMM-pages.js:137 [Pages]: received a notification to change to the hidden page "screenSaver" of type "string"
MMM-pages.js:304 [Pages]: Was asked to pause but rotation is already paused!
setRotation @ MMM-pages.js:304
notificationReceived @ MMM-pages.js:138
sendNotification @ main.js:99
sendNotification @ main.js:650
sendNotification @ module.js:341
doMenuAction @ MMM-OnScreenMenu.js:203
(anonymous) @ MMM-OnScreenMenu.js:313
module.js:182 alert is suspended.
module.js:182 MMM-pages is suspended.
module.js:182 MMM-Cursor is suspended.
module.js:182 calendar is suspended.
module.js:182 compliments is suspended.
2module.js:182 weather is suspended.
module.js:182 MMM-RAIN-MAP is suspended.
module.js:182 MMM-Globe is suspended.
module.js:182 newsfeed is suspended.
MMM-Tools.js:186 MMM-Tools is suspended.
module.js:182 MMM-ViewNotifications is suspended.
module.js:182 MMM-page-indicator is suspended.
module.js:189 clock is resumed.
module.js:189 MMM-OnScreenMenu is resumed.
module.js:189 MMM-TouchButton is resumed.

MMM-OnScreenMenu.js:195 OSM Menu Item Clicked: notify3
{"title":"Wake Up","icon":"refresh","notification":"LEAVE_HIDDEN_PAGE","payload":""}
MMM-pages.js:142 [Pages]: received a notification to leave the current hidden page 
module.js:182 alert is suspended.
module.js:182 MMM-pages is suspended.
module.js:182 MMM-Cursor is suspended.
MMM-pages.js:306 [Pages]: resuming rotation
module.js:182 compliments is suspended.
MMM-Tools.js:186 MMM-Tools is suspended.
module.js:189 clock is resumed.
module.js:189 calendar is resumed.
2module.js:189 weather is resumed.
module.js:189 MMM-RAIN-MAP is resumed.
module.js:189 MMM-Globe is resumed.
module.js:189 newsfeed is resumed.
module.js:189 MMM-OnScreenMenu is resumed.
module.js:189 MMM-TouchButton is resumed.
module.js:189 MMM-ViewNotifications is resumed.
module.js:189 MMM-page-indicator is resumed.

OSM Menu Item Clicked: notify1
{"title":"Sleep Page","icon":"refresh","notification":"SHOW_HIDDEN_PAGE","payload":"screenSaver"}
MMM-pages.js:137 [Pages]: received a notification to change to the hidden page "screenSaver" of type "string"
MMM-pages.js:306 [Pages]: pausing rotation

MMM-pages.js:309 Uncaught TypeError: this.timer_clear_function is not a function
    at Class.setRotation (MMM-pages.js:309:14)
    at Class.notificationReceived (MMM-pages.js:138:14)
    at sendNotification (main.js:99:12)
    at Object.sendNotification (main.js:650:4)
    at Class.sendNotification (module.js:341:6)
    at Class.doMenuAction (MMM-OnScreenMenu.js:203:18)
    at HTMLSpanElement.<anonymous> (MMM-OnScreenMenu.js:313:22)

setRotation @ MMM-pages.js:309
notificationReceived @ MMM-pages.js:138
sendNotification @ main.js:99
sendNotification @ main.js:650
sendNotification @ module.js:341
doMenuAction @ MMM-OnScreenMenu.js:203
(anonymous) @ MMM-OnScreenMenu.js:313

Temp fix:  comment out 

MMM-pages.js:309  this.timer_clear_function

Result:

MMM-OnScreenMenu and MMM-TouchButtons return to normal operation.

**Comment by sdetweil** [comment]
go to the module folder and do git pull

thanks for the great traceback

**Comment by sdetweil** [comment]
@KimORichter did u try the fix?

**Comment by KimORichter** [comment]
yes and it is working.  Thank you,

Kim
